<?php
namespace verbb\formie\helpers;

/** Accepted portable settings. Ownership, component classes and database IDs are never configurable here. */
class FormDocumentSchema
{
    // Constants
    // =========================================================================

    public const FORM = ['title', 'handle', 'userDeletedAction', 'fileUploadsAction', 'dataRetention', 'dataRetentionValue'];
    public const FORM_SETTINGS = [
        'displayFormTitle',
        'displayCurrentPageTitle',
        'displayPageTabs',
        'displayPageProgress',
        'scrollToTop',
        'progressCalculation',
        'progressPosition',
        'progressValuePosition',
        'defaultLabelPosition',
        'defaultInstructionsPosition',
        'defaultErrorMessagePosition',
        'requiredIndicator',
        'submitMethod',
        'submitAction',
        'submitActionTab',
        'submitActionUrl',
        'enableRedirectRules',
        'redirectRules',
        'submitActionFormHide',
        'automaticSubmissionState',
        'submitActionMessage',
        'submitActionMessageTimeout',
        'submitActionMessagePosition',
        'loadingIndicator',
        'loadingIndicatorText',
        'validationOnSubmit',
        'validationOnFocus',
        'disableSubmitButtonUntilValid',
        'errorMessage',
        'errorMessagePosition',
        'requireUser',
        'requireUserMessage',
        'scheduleForm',
        'scheduleFormStart',
        'scheduleFormEnd',
        'scheduleFormPendingMessage',
        'scheduleFormExpiredMessage',
        'limitSubmissions',
        'limitSubmissionsScope',
        'limitSubmissionsNumber',
        'limitSubmissionsType',
        'limitSubmissionsMessage',
        'limitSubmissionsIpAddressNumber',
        'limitSubmissionsIpAddressType',
        'limitSubmissionsIpAddressMessage',
        'integrations',
        'integrationDispatch',
        'integrationPolicies',
        'submissionTitleFormat',
        'collectIp',
        'collectUser',
        'cpSubmissionFieldConditions',
        'enableStatusRules',
        'statusRules',
        'enableDefaultClientEvents',
        'defaultClientEvents',
        'allowedStatusIds',
        'dataRetention',
        'dataRetentionValue',
        'fileUploadsAction',
        'usePerFormPermissions',
        'scoringEnabled',
        'quizPassPercentage',
        'quizAllowRetakes',
        'quizShowScoreAfterSubmit',
        'redirectUrl',
        'pageRedirectUrl',
        'defaultEmailTemplateId',
        'disableCaptchas',
    ];
    public const NOTIFICATION = [
        'name',
        'handle',
        'enabled',
        'subject',
        'recipients',
        'to',
        'toConditions',
        'cc',
        'bcc',
        'replyTo',
        'replyToName',
        'from',
        'fromName',
        'sender',
        'content',
        'attachFiles',
        'attachPdf',
        'attachAssets',
        'enableConditions',
        'conditions',
        'dispatchTiming',
        'customSettings',
    ];
    public const FORM_TEMPLATE = [
        'useCustomTemplates',
        'outputCss',
        'outputJs',
        'outputCssLocation',
        'outputJsLocation',
        'name',
        'handle',
        'template',
        'sortOrder',
        'copyTemplates',
        'hasSingleTemplate',
    ];
    public const EMAIL_TEMPLATE = [
        'hasSingleTemplate',
        'name',
        'handle',
        'template',
        'sortOrder',
        'copyTemplates',
    ];
    public const PDF_TEMPLATE = [
        'filenameFormat',
        'hasSingleTemplate',
        'name',
        'handle',
        'template',
        'sortOrder',
        'copyTemplates',
    ];
}
