export const DEFAULT_WAIT_FOR_VALUE_MS = 2000;
export const CAPTCHA_PROVIDER_LOAD_TIMEOUT_MS = 5000;
export const CAPTCHA_SUBMIT_WAIT_FOR_VALUE_MS = 5000;
export const CAPTCHA_EXECUTE_WAIT_FOR_VALUE_MS = 120000;
